apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www
  namespace: nhq-pin
spec:
  storageClassName: my-storage-class
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/data"
    type: Directory
