kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nhq-pvc
  namespace: nhq-pin
spec:
  storageClassName: my-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
