apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nhq-binding
  namespace: nhq-pin
subjects:
- kind: User
  name: nhq
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: nhq
  apiGroup: rbac.authorization.k8s.io
