apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: nhq-pin
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: pin30227@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx

---

apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: minisys-ingress
  namespace: nhq-pin
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nhq.id.vn
    secretName: nhq-tls
  rules:
  - host: nhq.id.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minisys-service
            port:
              number: 80
