apiVersion: v1
data:
  Corefile: |
    example.abc:53 {
        hosts {
          1.2.3.4 example.abc
          2.3.4.5 server.example.abc
          fallthrough
        }
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local calico in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-19T09:13:25Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "14609467"
  uid: aa7ab8fa-40a6-4971-9f64-deae31424ffd
