apiVersion: v1
kind: Service
metadata:
 annotations:
   loadbalancer.openstack.org/class: "cmc-loadbalancer-public"
 name: nhq-lb
 labels:
   app: web
spec:
 ports:
 - port: 8080
   targetPort: 80
   protocol: TCP
 selector:
   app: web
 type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:  
 name: lb
 namespace: ingress-nginx
 labels:
   app: web
spec:
 ports:
 - port: 8080
   targetPort: 80
   protocol: TCP
 selector:
   app: web
 type: ClusterIP