apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoibmhxaHViIiwicGFzc3dvcmQiOiIyMTMyMjFNb29uQFBpbiIsImF1dGgiOiJibWh4YUhWaU9qSXhNekl5TVUxdmIyNUFVR2x1In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2024-08-07T08:04:51Z"
  name: nhq-dockerhub
  namespace: default
  resourceVersion: "11249581"
  uid: 92c4b1ff-f2c6-47ba-9329-b0a66b75bc79
type: kubernetes.io/dockerconfigjson
