apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: nhq-pin
spec:
  volumes:
    - name: test-pv
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: test-pod-pv
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-pv


