apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: nhq-pin
  labels:
    type: storage
spec:
  storageClassName: nhq-pv-class
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/www"
