apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: nhq-pin
spec:
  storageClassName: nhq-pv-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
