apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-claim
  namespace: nhq-pin
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "nhq-pv-class" # required for static provisioning
  resources:
    requests:
      storage: 1Gi # ignored, required
  volumeName: s3-pv
